sudo: false
language: node_js
node_js:
  - node
  - 6

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - bash <(curl -s https://codecov.io/bash)
