sudo: false
language: node_js
node_js:
  - node
  - 6

addons:
  code_climate:
    repo_token: 540fa4e3b1b1a4eba8a54a7275cae7784900efce1149f65791c43aa6f6ed0f97

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - npm install codeclimate-test-reporter codacy-coverage
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
  - rm -rf ./coverage
